import _config_setup_ as setup
import _config_constants_ as cons

POS_RATIO = 0.34213
NEG_RATIO = 0.15659
NEU_RATIO = 0.50128

LABEL_LIMIT = int(setup.LABEL_RATIO * cons.DATA_SET_SIZE)
POS_COUNT_LIMIT = int(LABEL_LIMIT * POS_RATIO)
NEG_COUNT_LIMIT = int(LABEL_LIMIT * NEG_RATIO)
NEU_COUNT_LIMIT = int(LABEL_LIMIT * NEU_RATIO)


# CONSTANT RELATED TO SELF-TRAINING

TEST_LIMIT = setup.TEST_LIMIT
INCREMENT_LIMIT = setup.INCREMENT_LIMIT
NO_OF_ITERATION = setup.NO_OF_ITERATION

FEATURE_SET_CODE = setup.FEATURE_SET_CODE

DEFAULT_CLASSIFIER = setup.DEFAULT_CLASSIFIER

if DEFAULT_CLASSIFIER == cons.CLASSIFIER_SVM:
    DEFAULT_KERNEL = setup.DEFAULT_KERNEL
    DEFAULT_C_PARAMETER = setup.DEFAULT_C_PARAMETER
    DEFAULT_GAMMA_SVM = setup.DEFAULT_GAMMA_SVM
    DEFAULT_CLASS_WEIGHTS = setup.DEFAULT_CLASS_WEIGHTS
elif DEFAULT_CLASSIFIER == cons.CLASSIFIER_XGBOOST:
    DEFAULT_LEARNING_RATE = setup.DEFAULT_LEARNING_RATE
    DEFAULT_MAX_DEPTH = setup.DEFAULT_MAX_DEPTH
    DEFAULT_MIN_CHILD_WEIGHT = setup.DEFAULT_MIN_CHILD_WEIGHT
    DEFAULT_SILENT = setup.DEFAULT_SILENT
    DEFAULT_OBJECTIVE = setup.DEFAULT_OBJECTIVE
    DEFAULT_SUB_SAMPLE = setup.DEFAULT_SUB_SAMPLE
    DEFAULT_GAMMA_XBOOST = setup.DEFAULT_GAMMA_XBOOST
    DEFAULT_REGRESSION_ALPHA = setup.DEFAULT_REGRESSION_ALPHA
    DEFAULT_N_ESTIMATORS = setup.DEFAULT_N_ESTIMATORS
    DEFAULT_COLSAMPLE_BYTREE = setup.DEFAULT_COLSAMPLE_BYTREE

# HEADER OF THE SAVING FILE

CSV_HEADER = ["PositiveTrainSet", "NegativeTrainSet", "NeutralTrainSet",
              "FeatureSetCode", "TestSetLimit", "Iteration", "Accuracy",
              "PrecisionPositive", "PrecisionNegative", "PrecisionNeutral",
              "RecallPositive", "RecallNegative", "RecallNeutral",
              "fScorePositive", "fScoreNegative", "fScoreAverage"]

