import _config_constants_ as cons
import _config_setup_ as setup

LABEL_LIMIT = int(setup.LABEL_RATIO * cons.DATA_SET_SIZE)
POS_COUNT_LIMIT = int(LABEL_LIMIT * cons.POS_RATIO)
NEG_COUNT_LIMIT = int(LABEL_LIMIT * cons.NEG_RATIO)
NEU_COUNT_LIMIT = int(LABEL_LIMIT * cons.NEU_RATIO)

# CONSTANT RELATED TO SELF-TRAINING

TEST_LIMIT = setup.TEST_LIMIT
NO_OF_ITERATION = setup.NO_OF_ITERATION

FEATURE_SET_CODE = setup.FEATURE_SET_CODE

DEFAULT_CLASSIFIER = setup.DEFAULT_CLASSIFIER

if DEFAULT_CLASSIFIER == cons.CLASSIFIER_SVM:
    DEFAULT_KERNEL = setup.DEFAULT_KERNEL
    DEFAULT_C_PARAMETER = setup.DEFAULT_C_PARAMETER
    DEFAULT_GAMMA_SVM = setup.DEFAULT_GAMMA_SVM
    DEFAULT_CLASS_WEIGHTS = setup.DEFAULT_CLASS_WEIGHTS


